language: node_js
node_js:
  - "6"
  - "8"
  - "10"

env:
  - NODE_ENV=development

cache:
  directories:
    - "node_modules"

after_success:
  - npm i -g codecov
  - codecov

notifications:
  email: false
